// Code generated by fyne-theme-generator

package theme

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
)

type WoodlandTheme struct{}

func (WoodlandTheme) Color(c fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	switch c {
	case theme.ColorNameBackground:
		return color.NRGBA{R: 0x34, G: 0x1e, B: 0x14, A: 0xb9}
	case theme.ColorNameButton:
		return color.NRGBA{R: 0x4e, G: 0x75, B: 0x39, A: 0xeb}
	case theme.ColorNameDisabledButton:
		return color.NRGBA{R: 0x39, G: 0x5b, B: 0x26, A: 0xab}
	case theme.ColorNameDisabled:
		return color.NRGBA{R: 0xcd, G: 0xa7, B: 0x97, A: 0xb9}
	case theme.ColorNameError:
		return color.NRGBA{R: 0xe6, G: 0x44, B: 0x43, A: 0xff}
	case theme.ColorNameFocus:
		return color.NRGBA{R: 0xfd, G: 0x74, B: 0x10, A: 0xab}
	case theme.ColorNameForeground:
		return color.NRGBA{R: 0xdf, G: 0xc1, B: 0xb5, A: 0xfe}
	case theme.ColorNameHover:
		return color.NRGBA{R: 0xfd, G: 0x74, B: 0x11, A: 0x9b}
	case theme.ColorNameInputBackground:
		return color.NRGBA{R: 0x55, G: 0x35, B: 0x27, A: 0xb9}
	case theme.ColorNameInputBorder:
		return color.NRGBA{R: 0x3a, G: 0x24, B: 0x1b, A: 0x00}
	case theme.ColorNameMenuBackground:
		return color.NRGBA{R: 0x55, G: 0x35, B: 0x27, A: 0xff}
	case theme.ColorNamePlaceHolder:
		return color.NRGBA{R: 0xdf, G: 0xc0, B: 0xb4, A: 0x7f}
	case theme.ColorNamePressed:
		return color.NRGBA{R: 0xdf, G: 0xc0, B: 0xb4, A: 0xa4}
	case theme.ColorNamePrimary:
		return color.NRGBA{R: 0xfd, G: 0x74, B: 0x10, A: 0xab}
	case theme.ColorNameScrollBar:
		return color.NRGBA{R: 0x39, G: 0x5b, B: 0x26, A: 0xa8}
	case theme.ColorNameShadow:
		return color.NRGBA{R: 0x1d, G: 0xf, B: 0x9, A: 0xb9}
	default:
		return theme.DefaultTheme().Color(c, v)
	}
}

func (WoodlandTheme) Font(s fyne.TextStyle) fyne.Resource {
	if s.Monospace {
		return theme.DefaultTheme().Font(s)
	}
	if s.Bold {
		if s.Italic {
			return fontPTSerifBoldItalicTtf
		}
		return fontPTSerifBoldTtf
	}
	if s.Italic {
		return fontPTSerifItalicTtf
	}
	return fontPTSerifRegularTtf
}

func (WoodlandTheme) Icon(n fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(n)
}

func (WoodlandTheme) Size(s fyne.ThemeSizeName) float32 {
	switch s {
	case theme.SizeNameCaptionText:
		return 15.25
	case theme.SizeNameInlineIcon:
		return 25
	case theme.SizeNamePadding:
		return 5
	case theme.SizeNameScrollBar:
		return 10
	case theme.SizeNameScrollBarSmall:
		return 3
	case theme.SizeNameSeparatorThickness:
		return 2
	case theme.SizeNameText:
		return 15.25
	case theme.SizeNameInputBorder:
		return 2
	default:
		return theme.DefaultTheme().Size(s)
	}
}
