// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendars.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendar (id, name, description, created_at, updated_at, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW(),
    $3
)
RETURNING id, name, description, created_at, updated_at, user_id
`

type CreateCalendarParams struct {
	Name        string
	Description sql.NullString
	UserID      uuid.UUID
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, createCalendar, arg.Name, arg.Description, arg.UserID)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM calendar
WHERE id = $1
`

func (q *Queries) DeleteCalendar(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCalendar, id)
	return err
}

const getCalendarsByUserId = `-- name: GetCalendarsByUserId :many
SELECT id, name, description, created_at, updated_at, user_id FROM calendar
WHERE user_id = $1
ORDER BY updated_at ASC
`

func (q *Queries) GetCalendarsByUserId(ctx context.Context, userID uuid.UUID) ([]Calendar, error) {
	rows, err := q.db.QueryContext(ctx, getCalendarsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarByID = `-- name: UpdateCalendarByID :one
UPDATE calendar
SET name = $1, description = $2, updated_at = NOW()
WHERE id = $3
RETURNING id, name, description, created_at, updated_at, user_id
`

type UpdateCalendarByIDParams struct {
	Name        string
	Description sql.NullString
	ID          uuid.UUID
}

func (q *Queries) UpdateCalendarByID(ctx context.Context, arg UpdateCalendarByIDParams) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, updateCalendarByID, arg.Name, arg.Description, arg.ID)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
