// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eras.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEra = `-- name: CreateEra :one
INSERT INTO era (id, name, shorthand, start_year, description, created_at, updated_at, calendar_id, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    NOW(),
    NOW(),
    $5,
    $6
)
RETURNING id, name, shorthand, start_year, description, created_at, updated_at, calendar_id, user_id
`

type CreateEraParams struct {
	Name        string
	Shorthand   sql.NullString
	StartYear   int32
	Description sql.NullString
	CalendarID  uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) CreateEra(ctx context.Context, arg CreateEraParams) (Era, error) {
	row := q.db.QueryRowContext(ctx, createEra,
		arg.Name,
		arg.Shorthand,
		arg.StartYear,
		arg.Description,
		arg.CalendarID,
		arg.UserID,
	)
	var i Era
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Shorthand,
		&i.StartYear,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarID,
		&i.UserID,
	)
	return i, err
}

const deleteEra = `-- name: DeleteEra :exec
DELETE FROM era
WHERE id = $1
`

func (q *Queries) DeleteEra(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEra, id)
	return err
}

const getErasByCalendarId = `-- name: GetErasByCalendarId :many
SELECT id, name, shorthand, start_year, description, created_at, updated_at, calendar_id, user_id
FROM era
WHERE calendar_id = $1
ORDER BY start_year ASC
`

func (q *Queries) GetErasByCalendarId(ctx context.Context, calendarID uuid.UUID) ([]Era, error) {
	rows, err := q.db.QueryContext(ctx, getErasByCalendarId, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Era
	for rows.Next() {
		var i Era
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Shorthand,
			&i.StartYear,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CalendarID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEraById = `-- name: UpdateEraById :one
UPDATE era
SET name = $1, shorthand = $2, start_year = $3, description = $4, updated_at = NOW()
WHERE id = $5
RETURNING id, name, shorthand, start_year, description, created_at, updated_at, calendar_id, user_id
`

type UpdateEraByIdParams struct {
	Name        string
	Shorthand   sql.NullString
	StartYear   int32
	Description sql.NullString
	ID          uuid.UUID
}

func (q *Queries) UpdateEraById(ctx context.Context, arg UpdateEraByIdParams) (Era, error) {
	row := q.db.QueryRowContext(ctx, updateEraById,
		arg.Name,
		arg.Shorthand,
		arg.StartYear,
		arg.Description,
		arg.ID,
	)
	var i Era
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Shorthand,
		&i.StartYear,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarID,
		&i.UserID,
	)
	return i, err
}
