// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Calendar struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
}

type Month struct {
	ID          uuid.UUID
	Name        string
	MonthOrder  int32
	DaysInMonth int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CalendarID  uuid.UUID
	UserID      uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Weekday struct {
	ID         uuid.UUID
	Name       string
	DayOrder   int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	CalendarID uuid.UUID
	UserID     uuid.UUID
}
