// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: months.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMonth = `-- name: CreateMonth :one
INSERT INTO month (id, name, month_order, days_in_month, created_at, updated_at, calendar_id, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW(),
    NOW(),
    $4,
    $5
)
RETURNING id, name, month_order, days_in_month, created_at, updated_at, calendar_id, user_id
`

type CreateMonthParams struct {
	Name        string
	MonthOrder  int32
	DaysInMonth int32
	CalendarID  uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) CreateMonth(ctx context.Context, arg CreateMonthParams) (Month, error) {
	row := q.db.QueryRowContext(ctx, createMonth,
		arg.Name,
		arg.MonthOrder,
		arg.DaysInMonth,
		arg.CalendarID,
		arg.UserID,
	)
	var i Month
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthOrder,
		&i.DaysInMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarID,
		&i.UserID,
	)
	return i, err
}

const deleteMonth = `-- name: DeleteMonth :exec
DELETE FROM month
WHERE id = $1
`

func (q *Queries) DeleteMonth(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMonth, id)
	return err
}

const getMonthsByCalendarId = `-- name: GetMonthsByCalendarId :many
SELECT id, name, month_order, days_in_month, created_at, updated_at, calendar_id, user_id
FROM month
WHERE calendar_id = $1
ORDER BY month_order ASC
`

func (q *Queries) GetMonthsByCalendarId(ctx context.Context, calendarID uuid.UUID) ([]Month, error) {
	rows, err := q.db.QueryContext(ctx, getMonthsByCalendarId, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Month
	for rows.Next() {
		var i Month
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthOrder,
			&i.DaysInMonth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CalendarID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
