// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: universe.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUniverse = `-- name: CreateUniverse :one
INSERT INTO universe (id, name, description, created_at, updated_at, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW(),
    $3
)
RETURNING id, name, description, created_at, updated_at, user_id
`

type CreateUniverseParams struct {
	Name        string
	Description sql.NullString
	UserID      uuid.UUID
}

func (q *Queries) CreateUniverse(ctx context.Context, arg CreateUniverseParams) (Universe, error) {
	row := q.db.QueryRowContext(ctx, createUniverse, arg.Name, arg.Description, arg.UserID)
	var i Universe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getUniversesByUserId = `-- name: GetUniversesByUserId :many
SELECT id, name, description, created_at, updated_at, user_id FROM universe
WHERE user_id = $1
`

func (q *Queries) GetUniversesByUserId(ctx context.Context, userID uuid.UUID) ([]Universe, error) {
	rows, err := q.db.QueryContext(ctx, getUniversesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Universe
	for rows.Next() {
		var i Universe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
