// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weekdays.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWeekday = `-- name: CreateWeekday :one
INSERT INTO weekday (id, name, day_order, created_at, updated_at, calendar_id, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW(),
    $3,
    $4
)
RETURNING id, name, day_order, created_at, updated_at, calendar_id, user_id
`

type CreateWeekdayParams struct {
	Name       string
	DayOrder   int32
	CalendarID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) CreateWeekday(ctx context.Context, arg CreateWeekdayParams) (Weekday, error) {
	row := q.db.QueryRowContext(ctx, createWeekday,
		arg.Name,
		arg.DayOrder,
		arg.CalendarID,
		arg.UserID,
	)
	var i Weekday
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CalendarID,
		&i.UserID,
	)
	return i, err
}

const deleteWeekday = `-- name: DeleteWeekday :exec
DELETE FROM weekday
WHERE id = $1
`

func (q *Queries) DeleteWeekday(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWeekday, id)
	return err
}

const getWeekdaysByCalendarId = `-- name: GetWeekdaysByCalendarId :many
SELECT id, name, day_order, created_at, updated_at, calendar_id, user_id
FROM weekday
WHERE calendar_id = $1
ORDER BY day_order ASC
`

func (q *Queries) GetWeekdaysByCalendarId(ctx context.Context, calendarID uuid.UUID) ([]Weekday, error) {
	rows, err := q.db.QueryContext(ctx, getWeekdaysByCalendarId, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Weekday
	for rows.Next() {
		var i Weekday
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CalendarID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
