// Code generated by fyne-theme-generator

package gui

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
)

type DefaultTheme struct{}

func (DefaultTheme) Color(c fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	switch c {
	case theme.ColorNameBackground:
		return color.NRGBA{R: 0x1a, G: 0x2a, B: 0x33, A: 0xff}
	case theme.ColorNameButton:
		return color.NRGBA{R: 0x44, G: 0x55, B: 0x25, A: 0xff}
	case theme.ColorNameDisabledButton:
		return color.NRGBA{R: 0x44, G: 0x55, B: 0x25, A: 0x6f}
	case theme.ColorNameDisabled:
		return color.NRGBA{R: 0xff, G: 0xff, B: 0xff, A: 0x42}
	case theme.ColorNameError:
		return color.NRGBA{R: 0xf4, G: 0x43, B: 0x36, A: 0xff}
	case theme.ColorNameFocus:
		return color.NRGBA{R: 0x1c, G: 0x2f, B: 0x4a, A: 0x7f}
	case theme.ColorNameForeground:
		return color.NRGBA{R: 0xff, G: 0xff, B: 0xff, A: 0xff}
	case theme.ColorNameHover:
		return color.NRGBA{R: 0xfd, G: 0xfd, B: 0xfe, A: 0xf}
	case theme.ColorNameInputBackground:
		return color.NRGBA{R: 0x1c, G: 0x2f, B: 0x4b, A: 0xff}
	case theme.ColorNamePlaceHolder:
		return color.NRGBA{R: 0xb2, G: 0xb2, B: 0xb2, A: 0xff}
	case theme.ColorNamePressed:
		return color.NRGBA{R: 0xff, G: 0xff, B: 0xff, A: 0x66}
	case theme.ColorNamePrimary:
		return color.NRGBA{R: 0x6c, G: 0x7e, B: 0x3a, A: 0xff}
	case theme.ColorNameScrollBar:
		return color.NRGBA{R: 0x6c, G: 0x7e, B: 0x3a, A: 0xb6}
	case theme.ColorNameShadow:
		return color.NRGBA{R: 0x6c, G: 0x7e, B: 0x3a, A: 0x66}
	default:
		return theme.DefaultTheme().Color(c, v)
	}
}

func (DefaultTheme) Font(s fyne.TextStyle) fyne.Resource {
	if s.Monospace {
		return theme.DefaultTheme().Font(s)
	}
	if s.Bold {
		if s.Italic {
			return fontPTSerifBoldItalicTtf
		}
		return fontPTSerifBoldTtf
	}
	if s.Italic {
		return fontPTSerifItalicTtf
	}
	return fontPTSerifRegularTtf
}

func (DefaultTheme) Icon(n fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(n)
}

func (DefaultTheme) Size(s fyne.ThemeSizeName) float32 {
	switch s {
	case theme.SizeNameCaptionText:
		return 11
	case theme.SizeNameInlineIcon:
		return 20
	case theme.SizeNamePadding:
		return 4
	case theme.SizeNameScrollBar:
		return 10
	case theme.SizeNameScrollBarSmall:
		return 3
	case theme.SizeNameSeparatorThickness:
		return 1
	case theme.SizeNameText:
		return 15
	case theme.SizeNameInputBorder:
		return 2
	default:
		return theme.DefaultTheme().Size(s)
	}
}
